
namespace UpdateControls.Light.UnitTest
{
    public class Child
    {
        private Parent _mom;
        private Parent _dad;

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indMom = new Independent();
        private Independent _indDad = new Independent();

        public Parent Mom
        {
            get { _indMom.OnGet(); return _mom; }
            set { _indMom.OnSet(); _mom = value; }
        }

        public Parent Dad
        {
            get { _indDad.OnGet(); return _dad; }
            set { _indDad.OnSet(); _dad = value; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
