using System;
using UpdateControls;

namespace UpdateControls.Light.UnitTest
{
	public class Game
	{
        private int _score;

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indScore = new Independent();

        public int Score
        {
            get { _indScore.OnGet(); return _score; }
            set { _indScore.OnSet(); _score = value; }
        }
        // End generated code --------------------------------
        #endregion
	}
}
