using System;
using UpdateControls;
using System.Collections.Generic;

namespace UpdateControls.Light.UnitTest
{
    public class Game
	{
        private int _score;
        private List<Move> _moves = new List<Move>();

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indMoves = new Independent();
        private Independent _indScore = new Independent();

        public int Score
        {
            get { _indScore.OnGet(); return _score; }
            set { _indScore.OnSet(); _score = value; }
        }

        public Move NewMove()
        {
            _indMoves.OnSet();
            Move move = new Move();
            _moves.Add(move);
            return move;
        }

        public void DeleteMove(Move move)
        {
            _indMoves.OnSet();
            _moves.Remove(move);
        }

        public IEnumerable<Move> Moves
        {
            get { _indMoves.OnGet(); return _moves; }
        }
        // End generated code --------------------------------
        #endregion
	}
}
