using System.Collections.Generic;

namespace UpdateControls.Light.UnitTest
{
    public class Parent
    {
        private List<Child> _children = new List<Child>();

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indChildren = new Independent();

        public void AddChild(Child child)
        {
            _indChildren.OnSet();
            _children.Add(child);
        }

        public void RemoveChild(Child child)
        {
            _indChildren.OnSet();
            _children.Remove(child);
        }

        public IEnumerable<Child> Children
        {
            get { _indChildren.OnGet(); return _children; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
