using System;
using UpdateControls;

namespace UpdateControls.Light.UnitTest
{
    public class Tournament
	{
		private Game _selectedGame;

		#region Independent properties
		// Generated by Update Controls --------------------------------
		private Independent _indSelectedGame = new Independent();

		public Game SelectedGame
		{
			get { _indSelectedGame.OnGet(); return _selectedGame; }
			set { _indSelectedGame.OnSet(); _selectedGame = value; }
		}
		// End generated code --------------------------------
		#endregion
	}
}
