using System;
using UpdateControls;

namespace UpdateControls.Test
{
	public class ContactListNavigationModel
	{
		private Person _selectedPerson;

		#region Independent properties
		// Generated by Update Controls --------------------------------
		private Independent _indSelectedPerson = new Independent();

		public Person SelectedPerson
		{
			get { _indSelectedPerson.OnGet(); return _selectedPerson; }
			set { _indSelectedPerson.OnSet(); _selectedPerson = value; }
		}
		// End generated code --------------------------------
		#endregion
	}
}
