using System;
using UpdateControls;

namespace UpdateControls.Test
{
    public class Person
	{
		private PrefixID _prefix;
		private string _first;
		private string _last;
		private GenderEnum _gender;
		private Person _spouse;

		#region Independent properties
		// Generated by Update Controls --------------------------------
		private Independent _indPrefix = new Independent();
		private Independent _indFirst = new Independent();
		private Independent _indLast = new Independent();
		private Independent _indGender = new Independent();
		private Independent _indSpouse = new Independent();

		public PrefixID Prefix
		{
			get { _indPrefix.OnGet(); return _prefix; }
			set { _indPrefix.OnSet(); _prefix = value; }
		}

		public string First
		{
			get { _indFirst.OnGet(); return _first; }
			set { _indFirst.OnSet(); _first = value; }
		}

		public string Last
		{
			get { _indLast.OnGet(); return _last; }
			set { _indLast.OnSet(); _last = value; }
		}

		public GenderEnum Gender
		{
			get { _indGender.OnGet(); return _gender; }
			set { _indGender.OnSet(); _gender = value; }
		}

		public Person Spouse
		{
			get { _indSpouse.OnGet(); return _spouse; }
			private set { _indSpouse.OnSet(); _spouse = value; }
		}
		// End generated code --------------------------------
		#endregion

		public string FullName
		{
			get
            {
        		return string.Format("{0}{1} {2}",
					Prefix == PrefixID.Mr ? "Mr. " :
					Prefix == PrefixID.Mrs ? "Mrs. " :
					Prefix == PrefixID.Miss ? "Miss " :
					Prefix == PrefixID.Dr ? "Dr. " :
						"",
					First,
					Last);
            }
		}

        public static void Marry(Person a, Person b)
        {
            // If either person is already married,
            // annul that marriage.
            if (a != null && a.Spouse != null)
            {
                a.Spouse.Spouse = null;
                a.Spouse = null;
            }

            if (b != null && b.Spouse != null)
            {
                b.Spouse.Spouse = null;
                b.Spouse = null;
            }

            // Marry the two people
            if (a != null && b != null)
            {
                a.Spouse = b;
                b.Spouse = a;
            }
        }
	}
}
