
using System;
using System.Threading;
namespace UpdateControls.UnitTest
{
	public class SourceData
	{
		private int _sourceProperty;
		private AutoResetEvent _continue = new AutoResetEvent(false);

		#region Independent properties
		// Generated by Update Controls --------------------------------
		private Independent _indSourceProperty = new Independent();

		public int SourceProperty
		{
			get
			{
				_indSourceProperty.OnGet();
				int result = _sourceProperty;
				ThreadPool.QueueUserWorkItem(o =>
				{
					if (AfterGet != null)
						AfterGet();
					_continue.Set();
				});
				_continue.WaitOne();
				return result;
			}
			set { _indSourceProperty.OnSet(); _sourceProperty = value; }
		}
		// End generated code --------------------------------
		#endregion

		public event Action AfterGet;
	}
}
