/**********************************************************************
 * 
 * Update Controls .NET
 * Copyright 2010 Michael L Perry
 * Licensed under LGPL
 * 
 * http://updatecontrols.net
 * http://www.codeplex.com/updatecontrols/
 * 
 **********************************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace UpdateControls.Test
{
    public class Document
    {
        private List<Person> _people = new List<Person>();
        private List<Company> _companies = new List<Company>();

        #region Dynamic properties
        // Generated by Update Controls --------------------------------
        private Independent _dynPeople = new Independent();
        private Independent _dynCompanies = new Independent();

        public Person NewPerson()
        {
            _dynPeople.OnSet();
            Person person = new Person();
            _people.Add(person);
            return person;
        }

        public void DeletePerson(Person person)
        {
            _dynPeople.OnSet();
            _people.Remove(person);
        }

        public IEnumerable<Person> People
        {
            get { _dynPeople.OnGet(); return _people; }
        }

        public Company NewCompanie()
        {
            _dynCompanies.OnSet();
            Company companie = new Company();
            _companies.Add(companie);
            return companie;
        }

        public void DeleteCompanie(Company companie)
        {
            _dynCompanies.OnSet();
            _companies.Remove(companie);
        }

        public IEnumerable<Company> Companies
        {
            get { _dynCompanies.OnGet(); return _companies; }
        }
        // End generated code --------------------------------
        #endregion

        public Document()
        {
            Company handmark = new Company();
            Company ssg = new Company();
            Company nextCorp = new Company();
            handmark.Name = "Handmark";
            ssg.Name = "SSG";
            nextCorp.Name = "NextCorp";
            _companies.Add(handmark);
            _companies.Add(ssg);
            _companies.Add(nextCorp);
            Person mike = new Person();
            mike.Name = "Michael L Perry";
            mike.Employer = ssg;
            _people.Add(mike);
            Person russell = new Person();
            russell.Name = "Russell Elledge";
            russell.Employer = handmark;
            _people.Add(russell);
            Person allen = new Person();
            allen.Name = "Allen Davis";
            allen.Employer = handmark;
            _people.Add(allen);
        }
    }
}
