using System;
using UpdateControls;

namespace UpdateControls.XAML.Test
{
	public class Person
	{
		private string _first;
		private string _last;
		private GenderEnum _gender;
		private Person _spouse;

		#region Independent properties
		// Generated by Update Controls --------------------------------
		private Independent _indFirst = new Independent();
		private Independent _indLast = new Independent();
		private Independent _indGender = new Independent();
		private Independent _indSpouse = new Independent();

		public string First
		{
			get { _indFirst.OnGet(); return _first; }
			set { _indFirst.OnSet(); _first = value; }
		}

		public string Last
		{
			get { _indLast.OnGet(); return _last; }
			set { _indLast.OnSet(); _last = value; }
		}

		public GenderEnum Gender
		{
			get { _indGender.OnGet(); return _gender; }
			set { _indGender.OnSet(); _gender = value; }
		}

		public Person Spouse
		{
			get { _indSpouse.OnGet(); return _spouse; }
			set { _indSpouse.OnSet(); _spouse = value; }
		}
		// End generated code --------------------------------
		#endregion

		public string FullName
		{
			get { return string.Format("{0}, {1}", Last, First); }
		}
	}
}
