using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UpdateControls;

namespace UpdateControls.XAML.Test
{
    public class Person
    {
        private string _firstName;
        private string _lastName;
        private int _displayStrategy;

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indDisplayStrategy = new Independent();
        private Independent _indFirstName = new Independent();
        private Independent _indLastName = new Independent();

        public string FirstName
        {
            get { _indFirstName.OnGet(); return _firstName; }
            set { _indFirstName.OnSet(); _firstName = value; }
        }

        public string LastName
        {
            get { _indLastName.OnGet(); return _lastName; }
            set { _indLastName.OnSet(); _lastName = value; }
        }

        public int DisplayStrategy
        {
            get { _indDisplayStrategy.OnGet(); return _displayStrategy; }
            set { _indDisplayStrategy.OnSet(); _displayStrategy = value; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
