using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UpdateControls;

namespace UpdateControls.XAML.Test
{
    public class PersonList
    {
        private List<Person> _people = new List<Person>();

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indPeople = new Independent();

        public Person NewPerson()
        {
            _indPeople.OnSet();
            Person person = new Person();
            _people.Add(person);
            return person;
        }

        public void DeletePerson(Person person)
        {
            _indPeople.OnSet();
            _people.Remove(person);
        }

        public IEnumerable<Person> People
        {
            get { _indPeople.OnGet(); return _people; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
