/**********************************************************************
 * 
 * Update Controls .NET
 * Copyright 2008 Mallard Software Designs
 * Licensed under LGPL
 * 
 * http://updatecontrols.net
 * http://www.codeplex.com/updatecontrols/
 * 
 **********************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using UpdateControls;

namespace UpdateControls.Test
{
    public class Company
    {
        private string _name;

        #region Dynamic properties
        // Generated by Update Controls --------------------------------
        private Dynamic _dynName = new Dynamic();

        public string Name
        {
            get { _dynName.OnGet(); return _name; }
            set { _dynName.OnSet(); _name = value; }
        }
        // End generated code --------------------------------
        #endregion

        public override string ToString()
        {
            return Name;
        }
    }
}
