/**********************************************************************
 * 
 * Update Controls .NET
 * Copyright 2008 Mallard Software Designs
 * Licensed under LGPL
 * 
 * http://updatecontrols.net
 * http://www.codeplex.com/updatecontrols/
 * 
 **********************************************************************/

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using UpdateControls;

namespace UpdateControls.Test
{
    public partial class HeaderForm : Form
    {
        bool _focused = false;
        string _text = "Got focus?";

        #region Dynamic properties
        // Generated by Update Controls --------------------------------
        private Dynamic _dynFocused = new Dynamic();
        private Dynamic _dynText = new Dynamic();

        public bool Focuseded
        {
            get { _dynFocused.OnGet(); return _focused; }
            set { _dynFocused.OnSet(); _focused = value; }
        }

        public string Texted
        {
            get { _dynText.OnGet(); return _text; }
            set { _dynText.OnSet(); _text = value; }
        }
        // End generated code --------------------------------
        #endregion

        public HeaderForm()
        {
            InitializeComponent();
        }

        private bool header_GetFocus()
        {
            return Focuseded;
        }

        private string header_GetText()
        {
            return Texted;
        }

        private void focusedCheckBox_SetChecked(bool value)
        {
            Focuseded = value;
        }

        private void headerTextBox_SetText(string value)
        {
            Texted = value;
        }
    }
}