/**********************************************************************
 * 
 * Update Controls .NET
 * Copyright 2008 Mallard Software Designs
 * Licensed under LGPL
 * 
 * http://updatecontrols.net
 * http://www.codeplex.com/updatecontrols/
 * 
 **********************************************************************/

using System;
using System.Collections.Generic;
using System.Text;

namespace UpdateControls.Test
{
    public class Item
    {
        private string _name = string.Empty;
        private decimal _price = 0.0m;
        private int _quantity = 1;

        #region Dynamic properties
        // Generated by Update Controls --------------------------------
        private Dynamic _dynName = new Dynamic();
        private Dynamic _dynPrice = new Dynamic();
        private Dynamic _dynQuantity = new Dynamic();

        public string Name
        {
            get { _dynName.OnGet(); return _name; }
            set { _dynName.OnSet(); _name = value; }
        }

        public decimal Price
        {
            get { _dynPrice.OnGet(); return _price; }
            set { _dynPrice.OnSet(); _price = value; }
        }

        public int Quantity
        {
            get { _dynQuantity.OnGet(); return _quantity; }
            set { _dynQuantity.OnSet(); _quantity = value; }
        }
        // End generated code --------------------------------
        #endregion

        public decimal Total
        {
            get { return Price * Quantity; }
        }

        public string Validate()
        {
            if (Quantity < 1)
                return "Quantity must be at least 1.";
            else
                return "";
        }
    }
}
